"""estrutura inicial da app

Revision ID: 5489328eaaa8
Revises: 
Create Date: 2025-07-13 13:24:04.643840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5489328eaaa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=200), nullable=True),
    sa.Column('data_registo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('artista', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('dimensoes_cm', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('vendido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anuncio_categoria',
    sa.Column('anuncio_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('anuncio_id', 'categoria_id')
    )
    op.create_table('anuncio_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('anuncio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anuncio_tag',
    sa.Column('anuncio_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('anuncio_id', 'tag_id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('anuncio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('anuncio_id', sa.Integer(), nullable=False),
    sa.Column('data_adicao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('utilizador_id', 'anuncio_id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('anuncio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    op.drop_table('favoritos')
    op.drop_table('comentarios')
    op.drop_table('anuncio_tag')
    op.drop_table('anuncio_imagens')
    op.drop_table('anuncio_categoria')
    op.drop_table('anuncios')
    op.drop_table('utilizadores')
    op.drop_table('tags')
    op.drop_table('categorias')
    # ### end Alembic commands ###
